[package]
name = "xtask"
version = "0.0.2"
edition.workspace = true
publish = false
license.workspace = true

[dependencies]
clap.workspace = true
clap_mangen.workspace = true
git-filter-tree = { path = "../plumbing/git-filter-tree" }
git-set-attr = { path = "../plumbing/git-set-attr" }
